

export const metadata = {
  title: "Fiable Constructions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

      <main
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </main>

  );
}
