import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const montserrat = Montserrat({
  subsets: ["latin"], 
  // weight: [ "500"], 
  style: ["normal", "italic"],       
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} `}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
